-- MySQL Script generated by MySQL Workbench
-- 03/12/16 11:33:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema normdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `normdb` ;

-- -----------------------------------------------------
-- Schema normdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `normdb` DEFAULT CHARACTER SET utf8 ;
USE `normdb` ;

-- -----------------------------------------------------
-- Table `normdb`.`clinical_trial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `normdb`.`clinical_trial` ;

CREATE TABLE IF NOT EXISTS `normdb`.`clinical_trial` (
  `nctid` CHAR(12) NOT NULL,
  `title` TEXT NULL COMMENT 'title: title of the study',
  `topic` TEXT NULL COMMENT 'studytype: type of study',
  PRIMARY KEY (`nctid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `normdb`.`eligibility_criteria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `normdb`.`eligibility_criteria` ;

CREATE TABLE IF NOT EXISTS `normdb`.`eligibility_criteria` (
  `number` INT NOT NULL,
  `trial` VARCHAR(12) NOT NULL,
  `utterance` TEXT NULL COMMENT 'text: Utterance of the eligibility criteria',
  `inc_exc` INT NULL COMMENT 'type: inclusion or exclusion\n',
  PRIMARY KEY (`number`, `trial`),
  INDEX `fk_eligibilitycriteria_clinicaltrial_idx` (`trial` ASC),
  CONSTRAINT `fk_eligibilitycriteria_clinicaltrial`
    FOREIGN KEY (`trial`)
    REFERENCES `normdb`.`clinical_trial` (`nctid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `normdb`.`concept`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `normdb`.`concept` ;

CREATE TABLE IF NOT EXISTS `normdb`.`concept` (
  `sctid` VARCHAR(15) NOT NULL,
  `cui` VARCHAR(10) NULL,
  `fsn` VARCHAR(256) NULL,
  `hierarchy` VARCHAR(128) NULL COMMENT 'type: hierarchy in SNOMEDCT taxonomy',
  PRIMARY KEY (`sctid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `normdb`.`cmatch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `normdb`.`cmatch` ;

CREATE TABLE IF NOT EXISTS `normdb`.`cmatch` (
  `number` INT NOT NULL,
  `trial` VARCHAR(12) NOT NULL,
  `sctid` VARCHAR(15) NOT NULL,
  `phrase` TEXT NULL,
  `synonym` VARCHAR(256) NULL,
  `prefered_name` VARCHAR(256) NULL,
  `matched_words` VARCHAR(256) NULL,
  `semantic_types` VARCHAR(128) NULL,
  PRIMARY KEY (`number`, `trial`, `sctid`),
  INDEX `fk_eligibility_criteria_has_concept_concept1_idx` (`sctid` ASC),
  INDEX `fk_eligibility_criteria_has_concept_eligibility_criteria1_idx` (`number` ASC, `trial` ASC),
  CONSTRAINT `fk_eligibility_criteria_has_concept_eligibility_criteria1`
    FOREIGN KEY (`number` , `trial`)
    REFERENCES `normdb`.`eligibility_criteria` (`number` , `trial`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eligibility_criteria_has_concept_concept1`
    FOREIGN KEY (`sctid`)
    REFERENCES `normdb`.`concept` (`sctid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `normdb`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `normdb`.`attribute` ;

CREATE TABLE IF NOT EXISTS `normdb`.`attribute` (
  `trial` CHAR(12) NOT NULL,
  `attribute` VARCHAR(256) NOT NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`trial`, `attribute`),
  CONSTRAINT `fk_attribute_clinical_trial1`
    FOREIGN KEY (`trial`)
    REFERENCES `normdb`.`clinical_trial` (`nctid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
